version: '3'

services:
  faker-service:
    build: ./faker
    ports:
      - 5001:80

  db:
    image: mysql:5.7
    hostname: db
    env_file:
      - ./db/db.env
    ports:
      - 3306:3306
    volumes:
      - ./db/data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  api:
    build: ./api
    ports:
      - 5000:80
    depends_on:
      db:
        condition: service_healthy
    links:
      - db

  website:
    build: ./web
    ports:
      - "80-82:80"
    depends_on:
      - api


  nginx:
    image: nginx:1.13
    ports:
      - 8080:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - website
