version: '3'

services:
  api:
    build: ./api
    ports: 
      - 5000:80
    depends_on: 
      - database

  website:
    build: ./web
    ports:
      - 80:80
    depends_on:
      - api

  faker-service:
    build: ./faker
    ports:
      - 5001:80

  database:
    build: ./db
    hostname: database
    ports:
      - 3306:3306
    
    