version: '3'

services:
  faker-service:
    build: ./faker
    ports:
      - 5001:80

  db:
    image: mysql:5.7
    hostname: db
    env_file:
      - ./db/db.env
    ports:
      - 3306:3306
    volumes:
      - ./db/data:/var/lib/mysql

  api:
    build: ./api
    ports: 
      - 5000:80
    depends_on: 
      - db 
    links:
      - db

  website:
    build: ./web
    ports:
      - 80:80
    depends_on:
      - api

