version: '3'

services:
  api:
    build: ./api
    ports: 
      - 5000:80
    depends_on: 
      - db


  website:
    build: ./web
    ports:
      - 80:80
    depends_on:
      - api

  faker-service:
    build: ./faker
    ports:
      - 5001:80

  database:
    #build: ./db
    image: mysql:latest
    hostname: database
    environment:
      MYSQL_ROOT_PASSWORD: M@st3rRoot
      MYSQL_DATABASE: wafd
      MYSQL_USER: db_user
      MYSQL_PASSWORD: M4ster123
    ports:
      - 3306:3306
    volumes:
      - ./db:/var/lib/mysql
    